	testeio u0 (
		.chrom_seg_0_export              (<connected-to-chrom_seg_0_export>),              //              chrom_seg_0.export
		.chrom_seg_1_export              (<connected-to-chrom_seg_1_export>),              //              chrom_seg_1.export
		.chrom_seg_10_export             (<connected-to-chrom_seg_10_export>),             //             chrom_seg_10.export
		.chrom_seg_11_export             (<connected-to-chrom_seg_11_export>),             //             chrom_seg_11.export
		.chrom_seg_12_export             (<connected-to-chrom_seg_12_export>),             //             chrom_seg_12.export
		.chrom_seg_13_export             (<connected-to-chrom_seg_13_export>),             //             chrom_seg_13.export
		.chrom_seg_14_export             (<connected-to-chrom_seg_14_export>),             //             chrom_seg_14.export
		.chrom_seg_15_export             (<connected-to-chrom_seg_15_export>),             //             chrom_seg_15.export
		.chrom_seg_16_export             (<connected-to-chrom_seg_16_export>),             //             chrom_seg_16.export
		.chrom_seg_17_export             (<connected-to-chrom_seg_17_export>),             //             chrom_seg_17.export
		.chrom_seg_18_export             (<connected-to-chrom_seg_18_export>),             //             chrom_seg_18.export
		.chrom_seg_19_export             (<connected-to-chrom_seg_19_export>),             //             chrom_seg_19.export
		.chrom_seg_2_export              (<connected-to-chrom_seg_2_export>),              //              chrom_seg_2.export
		.chrom_seg_20_export             (<connected-to-chrom_seg_20_export>),             //             chrom_seg_20.export
		.chrom_seg_21_export             (<connected-to-chrom_seg_21_export>),             //             chrom_seg_21.export
		.chrom_seg_22_export             (<connected-to-chrom_seg_22_export>),             //             chrom_seg_22.export
		.chrom_seg_23_export             (<connected-to-chrom_seg_23_export>),             //             chrom_seg_23.export
		.chrom_seg_24_export             (<connected-to-chrom_seg_24_export>),             //             chrom_seg_24.export
		.chrom_seg_25_export             (<connected-to-chrom_seg_25_export>),             //             chrom_seg_25.export
		.chrom_seg_26_export             (<connected-to-chrom_seg_26_export>),             //             chrom_seg_26.export
		.chrom_seg_27_export             (<connected-to-chrom_seg_27_export>),             //             chrom_seg_27.export
		.chrom_seg_28_export             (<connected-to-chrom_seg_28_export>),             //             chrom_seg_28.export
		.chrom_seg_29_export             (<connected-to-chrom_seg_29_export>),             //             chrom_seg_29.export
		.chrom_seg_3_export              (<connected-to-chrom_seg_3_export>),              //              chrom_seg_3.export
		.chrom_seg_30_export             (<connected-to-chrom_seg_30_export>),             //             chrom_seg_30.export
		.chrom_seg_4_export              (<connected-to-chrom_seg_4_export>),              //              chrom_seg_4.export
		.chrom_seg_5_export              (<connected-to-chrom_seg_5_export>),              //              chrom_seg_5.export
		.chrom_seg_6_export              (<connected-to-chrom_seg_6_export>),              //              chrom_seg_6.export
		.chrom_seg_7_export              (<connected-to-chrom_seg_7_export>),              //              chrom_seg_7.export
		.chrom_seg_8_export              (<connected-to-chrom_seg_8_export>),              //              chrom_seg_8.export
		.chrom_seg_9_export              (<connected-to-chrom_seg_9_export>),              //              chrom_seg_9.export
		.clk_clk                         (<connected-to-clk_clk>),                         //                      clk.clk
		.correct_mem_s2_address          (<connected-to-correct_mem_s2_address>),          //           correct_mem_s2.address
		.correct_mem_s2_chipselect       (<connected-to-correct_mem_s2_chipselect>),       //                         .chipselect
		.correct_mem_s2_clken            (<connected-to-correct_mem_s2_clken>),            //                         .clken
		.correct_mem_s2_write            (<connected-to-correct_mem_s2_write>),            //                         .write
		.correct_mem_s2_readdata         (<connected-to-correct_mem_s2_readdata>),         //                         .readdata
		.correct_mem_s2_writedata        (<connected-to-correct_mem_s2_writedata>),        //                         .writedata
		.correct_mem_s2_byteenable       (<connected-to-correct_mem_s2_byteenable>),       //                         .byteenable
		.done_processing_chrom_export    (<connected-to-done_processing_chrom_export>),    //    done_processing_chrom.export
		.done_processing_feedback_export (<connected-to-done_processing_feedback_export>), // done_processing_feedback.export
		.error_sum_0_export              (<connected-to-error_sum_0_export>),              //              error_sum_0.export
		.error_sum_1_export              (<connected-to-error_sum_1_export>),              //              error_sum_1.export
		.error_sum_2_export              (<connected-to-error_sum_2_export>),              //              error_sum_2.export
		.error_sum_3_export              (<connected-to-error_sum_3_export>),              //              error_sum_3.export
		.error_sum_4_export              (<connected-to-error_sum_4_export>),              //              error_sum_4.export
		.error_sum_5_export              (<connected-to-error_sum_5_export>),              //              error_sum_5.export
		.error_sum_6_export              (<connected-to-error_sum_6_export>),              //              error_sum_6.export
		.error_sum_7_export              (<connected-to-error_sum_7_export>),              //              error_sum_7.export
		.expected_output_0_export        (<connected-to-expected_output_0_export>),        //        expected_output_0.export
		.expectedoutputs_export          (<connected-to-expectedoutputs_export>),          //          expectedoutputs.export
		.hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>), //                   hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),   //                         .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),   //                         .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),   //                         .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),   //                         .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),   //                         .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),   //                         .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_io_hps_io_emac1_inst_MDC>),    //                         .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>), //                         .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>), //                         .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>), //                         .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),   //                         .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),   //                         .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),   //                         .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),     //                         .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_io_hps_io_sdio_inst_D0>),      //                         .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_io_hps_io_sdio_inst_D1>),      //                         .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),     //                         .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_io_hps_io_sdio_inst_D2>),      //                         .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_io_hps_io_sdio_inst_D3>),      //                         .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_io_hps_io_usb1_inst_D0>),      //                         .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_io_hps_io_usb1_inst_D1>),      //                         .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_io_hps_io_usb1_inst_D2>),      //                         .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_io_hps_io_usb1_inst_D3>),      //                         .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_io_hps_io_usb1_inst_D4>),      //                         .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_io_hps_io_usb1_inst_D5>),      //                         .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_io_hps_io_usb1_inst_D6>),      //                         .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_io_hps_io_usb1_inst_D7>),      //                         .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_io_hps_io_usb1_inst_CLK>),     //                         .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_io_hps_io_usb1_inst_STP>),     //                         .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_io_hps_io_usb1_inst_DIR>),     //                         .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_io_hps_io_usb1_inst_NXT>),     //                         .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_io_hps_io_uart0_inst_RX>),     //                         .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_io_hps_io_uart0_inst_TX>),     //                         .hps_io_uart0_inst_TX
		.input_sequence_0_export         (<connected-to-input_sequence_0_export>),         //         input_sequence_0.export
		.inputsequences_export           (<connected-to-inputsequences_export>),           //           inputsequences.export
		.mem_s2_address                  (<connected-to-mem_s2_address>),                  //                   mem_s2.address
		.mem_s2_chipselect               (<connected-to-mem_s2_chipselect>),               //                         .chipselect
		.mem_s2_clken                    (<connected-to-mem_s2_clken>),                    //                         .clken
		.mem_s2_write                    (<connected-to-mem_s2_write>),                    //                         .write
		.mem_s2_readdata                 (<connected-to-mem_s2_readdata>),                 //                         .readdata
		.mem_s2_writedata                (<connected-to-mem_s2_writedata>),                //                         .writedata
		.mem_s2_byteenable               (<connected-to-mem_s2_byteenable>),               //                         .byteenable
		.memory_mem_a                    (<connected-to-memory_mem_a>),                    //                   memory.mem_a
		.memory_mem_ba                   (<connected-to-memory_mem_ba>),                   //                         .mem_ba
		.memory_mem_ck                   (<connected-to-memory_mem_ck>),                   //                         .mem_ck
		.memory_mem_ck_n                 (<connected-to-memory_mem_ck_n>),                 //                         .mem_ck_n
		.memory_mem_cke                  (<connected-to-memory_mem_cke>),                  //                         .mem_cke
		.memory_mem_cs_n                 (<connected-to-memory_mem_cs_n>),                 //                         .mem_cs_n
		.memory_mem_ras_n                (<connected-to-memory_mem_ras_n>),                //                         .mem_ras_n
		.memory_mem_cas_n                (<connected-to-memory_mem_cas_n>),                //                         .mem_cas_n
		.memory_mem_we_n                 (<connected-to-memory_mem_we_n>),                 //                         .mem_we_n
		.memory_mem_reset_n              (<connected-to-memory_mem_reset_n>),              //                         .mem_reset_n
		.memory_mem_dq                   (<connected-to-memory_mem_dq>),                   //                         .mem_dq
		.memory_mem_dqs                  (<connected-to-memory_mem_dqs>),                  //                         .mem_dqs
		.memory_mem_dqs_n                (<connected-to-memory_mem_dqs_n>),                //                         .mem_dqs_n
		.memory_mem_odt                  (<connected-to-memory_mem_odt>),                  //                         .mem_odt
		.memory_mem_dm                   (<connected-to-memory_mem_dm>),                   //                         .mem_dm
		.memory_oct_rzqin                (<connected-to-memory_oct_rzqin>),                //                         .oct_rzqin
		.nextsample_export               (<connected-to-nextsample_export>),               //               nextsample.export
		.preparingnextsample_export      (<connected-to-preparingnextsample_export>),      //      preparingnextsample.export
		.ready_to_process_export         (<connected-to-ready_to_process_export>),         //         ready_to_process.export
		.reset_reset_n                   (<connected-to-reset_reset_n>),                   //                    reset.reset_n
		.sequences_to_process_export     (<connected-to-sequences_to_process_export>),     //     sequences_to_process.export
		.start_processing_chrom_export   (<connected-to-start_processing_chrom_export>),   //   start_processing_chrom.export
		.startcomm_export                (<connected-to-startcomm_export>),                //                startcomm.export
		.valid_output_0_export           (<connected-to-valid_output_0_export>),           //           valid_output_0.export
		.validoutputs_export             (<connected-to-validoutputs_export>),             //             validoutputs.export
		.writesample_export              (<connected-to-writesample_export>)               //              writesample.export
	);

